server:
  port: 8080
  servlet:
    contextPath: /

spring:
  datasource:
    username: color_api_service
    password: 123
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/products
    driver-class-name: com.mysql.cj.jdbc.Driver
